#pragma once
#include <vector>
#include <string>
#include <SFML/Graphics.hpp>
#include <thread>
#include <cstdlib>
#include <chrono>
#include <map>
#include <fstream>
#include <sstream>
#include <memory>
