#pragma once
#include <vector>
#include <string>
#include <SFML/Graphics.hpp>
#include <thread>
#include <cstdlib>
#include <chrono>
#include <map>
#include <set>
#include <fstream>
#include <sstream>
#include <memory>
#include "imgui.h"
#include "imgui-SFML.h"
